# in yourapp/migrations/0003_insert_pokemon.py
from django.db import migrations
from django.core.exceptions import ValidationError

def insert_pokemon_first_generation(apps, schema_editor):
    Pokemon = apps.get_model('pokemonTeams', 'Pokemon')
    PokemonType = apps.get_model('pokemonTeams', 'PokemonType')

    # Define Pokémon data for the first generation
    pokemon_data_first_generation = [
        {"pokedex_id": 1, "name": "Bulbasaur", "types": ["Grass", "Poison"]},
        {"pokedex_id": 2, "name": "Ivysaur", "types": ["Grass", "Poison"]},
        {"pokedex_id": 3, "name": "Venusaur", "types": ["Grass", "Poison"]},
        {"pokedex_id": 4, "name": "Charmander", "types": ["Fire"]},
        {"pokedex_id": 5, "name": "Charmeleon", "types": ["Fire"]},
        {"pokedex_id": 6, "name": "Charizard", "types": ["Fire", "Flying"]},
        {"pokedex_id": 7, "name": "Squirtle", "types": ["Water"]},
        {"pokedex_id": 8, "name": "Wartortle", "types": ["Water"]},
        {"pokedex_id": 9, "name": "Blastoise", "types": ["Water"]},
        {"pokedex_id": 10, "name": "Caterpie", "types": ["Bug"]},
        {"pokedex_id": 11, "name": "Metapod", "types": ["Bug"]},
        {"pokedex_id": 12, "name": "Butterfree", "types": ["Bug", "Flying"]},
        {"pokedex_id": 13, "name": "Weedle", "types": ["Bug", "Poison"]},
        {"pokedex_id": 14, "name": "Kakuna", "types": ["Bug", "Poison"]},
        {"pokedex_id": 15, "name": "Beedrill", "types": ["Bug", "Poison"]},
        {"pokedex_id": 16, "name": "Pidgey", "types": ["Normal", "Flying"]},
        {"pokedex_id": 17, "name": "Pidgeotto", "types": ["Normal", "Flying"]},
        {"pokedex_id": 18, "name": "Pidgeot", "types": ["Normal", "Flying"]},
        {"pokedex_id": 19, "name": "Rattata", "types": ["Normal"]},
        {"pokedex_id": 20, "name": "Raticate", "types": ["Normal"]},
        {"pokedex_id": 21, "name": "Spearow", "types": ["Normal", "Flying"]},
        {"pokedex_id": 22, "name": "Fearow", "types": ["Normal", "Flying"]},
        {"pokedex_id": 23, "name": "Ekans", "types": ["Poison"]},
        {"pokedex_id": 24, "name": "Arbok", "types": ["Poison"]},
        {"pokedex_id": 25, "name": "Pikachu", "types": ["Electric"]},
        {"pokedex_id": 26, "name": "Raichu", "types": ["Electric"]},
        {"pokedex_id": 27, "name": "Sandshrew", "types": ["Ground"]},
        {"pokedex_id": 28, "name": "Sandslash", "types": ["Ground"]},
        {"pokedex_id": 29, "name": "Nidoran♀", "types": ["Poison"]},
        {"pokedex_id": 30, "name": "Nidorina", "types": ["Poison"]},
        {"pokedex_id": 31, "name": "Nidoqueen", "types": ["Poison", "Ground"]},
        {"pokedex_id": 32, "name": "Nidoran♂", "types": ["Poison"]},
        {"pokedex_id": 33, "name": "Nidorino", "types": ["Poison"]},
        {"pokedex_id": 34, "name": "Nidoking", "types": ["Poison", "Ground"]},
        {"pokedex_id": 35, "name": "Clefairy", "types": ["Normal"]},
        {"pokedex_id": 36, "name": "Clefable", "types": ["Normal"]},
        {"pokedex_id": 37, "name": "Vulpix", "types": ["Fire"]},
        {"pokedex_id": 38, "name": "Ninetales", "types": ["Fire"]},
        {"pokedex_id": 39, "name": "Jigglypuff", "types": ["Normal"]},
        {"pokedex_id": 40, "name": "Wigglytuff", "types": ["Normal"]},
        {"pokedex_id": 41, "name": "Zubat", "types": ["Poison", "Flying"]},
        {"pokedex_id": 42, "name": "Golbat", "types": ["Poison", "Flying"]},
        {"pokedex_id": 43, "name": "Oddish", "types": ["Grass", "Poison"]},
        {"pokedex_id": 44, "name": "Gloom", "types": ["Grass", "Poison"]},
        {"pokedex_id": 45, "name": "Vileplume", "types": ["Grass", "Poison"]},
        {"pokedex_id": 46, "name": "Paras", "types": ["Bug", "Grass"]},
        {"pokedex_id": 47, "name": "Parasect", "types": ["Bug", "Grass"]},
        {"pokedex_id": 48, "name": "Venonat", "types": ["Bug", "Poison"]},
        {"pokedex_id": 49, "name": "Venomoth", "types": ["Bug", "Poison"]},
        {"pokedex_id": 50, "name": "Diglett", "types": ["Ground"]},
        {"pokedex_id": 51, "name": "Dugtrio", "types": ["Ground"]},
        {"pokedex_id": 52, "name": "Meowth", "types": ["Normal"]},
        {"pokedex_id": 53, "name": "Persian", "types": ["Normal"]},
        {"pokedex_id": 54, "name": "Psyduck", "types": ["Water"]},
        {"pokedex_id": 55, "name": "Golduck", "types": ["Water"]},
        {"pokedex_id": 56, "name": "Mankey", "types": ["Fighting"]},
        {"pokedex_id": 57, "name": "Primeape", "types": ["Fighting"]},
        {"pokedex_id": 58, "name": "Growlithe", "types": ["Fire"]},
        {"pokedex_id": 59, "name": "Arcanine", "types": ["Fire"]},
        {"pokedex_id": 60, "name": "Poliwag", "types": ["Water"]},
        {"pokedex_id": 61, "name": "Poliwhirl", "types": ["Water"]},
        {"pokedex_id": 62, "name": "Poliwrath", "types": ["Water", "Fighting"]},
        {"pokedex_id": 63, "name": "Abra", "types": ["Psychic"]},
        {"pokedex_id": 64, "name": "Kadabra", "types": ["Psychic"]},
        {"pokedex_id": 65, "name": "Alakazam", "types": ["Psychic"]},
        {"pokedex_id": 66, "name": "Machop", "types": ["Fighting"]},
        {"pokedex_id": 67, "name": "Machoke", "types": ["Fighting"]},
        {"pokedex_id": 68, "name": "Machamp", "types": ["Fighting"]},
        {"pokedex_id": 69, "name": "Bellsprout", "types": ["Grass", "Poison"]},
        {"pokedex_id": 70, "name": "Weepinbell", "types": ["Grass", "Poison"]},
        {"pokedex_id": 71, "name": "Victreebel", "types": ["Grass", "Poison"]},
        {"pokedex_id": 72, "name": "Tentacool", "types": ["Water", "Poison"]},
        {"pokedex_id": 73, "name": "Tentacruel", "types": ["Water", "Poison"]},
        {"pokedex_id": 74, "name": "Geodude", "types": ["Rock", "Ground"]},
        {"pokedex_id": 75, "name": "Graveler", "types": ["Rock", "Ground"]},
        {"pokedex_id": 76, "name": "Golem", "types": ["Rock", "Ground"]},
        {"pokedex_id": 77, "name": "Ponyta", "types": ["Fire"]},
        {"pokedex_id": 78, "name": "Rapidash", "types": ["Fire"]},
        {"pokedex_id": 79, "name": "Slowpoke", "types": ["Water", "Psychic"]},
        {"pokedex_id": 80, "name": "Slowbro", "types": ["Water", "Psychic"]},
        {"pokedex_id": 81, "name": "Magnemite", "types": ["Electric", "Steel"]},
        {"pokedex_id": 82, "name": "Magneton", "types": ["Electric", "Steel"]},
        {"pokedex_id": 83, "name": "Farfetch'd", "types": ["Normal", "Flying"]},
        {"pokedex_id": 84, "name": "Doduo", "types": ["Normal", "Flying"]},
        {"pokedex_id": 85, "name": "Dodrio", "types": ["Normal", "Flying"]},
        {"pokedex_id": 86, "name": "Seel", "types": ["Water"]},
        {"pokedex_id": 87, "name": "Dewgong", "types": ["Water", "Ice"]},
        {"pokedex_id": 88, "name": "Grimer", "types": ["Poison"]},
        {"pokedex_id": 89, "name": "Muk", "types": ["Poison"]},
        {"pokedex_id": 90, "name": "Shellder", "types": ["Water"]},
        {"pokedex_id": 91, "name": "Cloyster", "types": ["Water", "Ice"]},
        {"pokedex_id": 92, "name": "Gastly", "types": ["Ghost", "Poison"]},
        {"pokedex_id": 93, "name": "Haunter", "types": ["Ghost", "Poison"]},
        {"pokedex_id": 94, "name": "Gengar", "types": ["Ghost", "Poison"]},
        {"pokedex_id": 95, "name": "Onix", "types": ["Rock", "Ground"]},
        {"pokedex_id": 96, "name": "Drowzee", "types": ["Psychic"]},
        {"pokedex_id": 97, "name": "Hypno", "types": ["Psychic"]},
        {"pokedex_id": 98, "name": "Krabby", "types": ["Water"]},
        {"pokedex_id": 99, "name": "Kingler", "types": ["Water"]},
        {"pokedex_id": 100, "name": "Voltorb", "types": ["Electric"]},
        {"pokedex_id": 101, "name": "Electrode", "types": ["Electric"]},
        {"pokedex_id": 102, "name": "Exeggcute", "types": ["Grass", "Psychic"]},
        {"pokedex_id": 103, "name": "Exeggutor", "types": ["Grass", "Psychic"]},
        {"pokedex_id": 104, "name": "Cubone", "types": ["Ground"]},
        {"pokedex_id": 105, "name": "Marowak", "types": ["Ground"]},
        {"pokedex_id": 106, "name": "Hitmonlee", "types": ["Fighting"]},
        {"pokedex_id": 107, "name": "Hitmonchan", "types": ["Fighting"]},
        {"pokedex_id": 108, "name": "Lickitung", "types": ["Normal"]},
        {"pokedex_id": 109, "name": "Koffing", "types": ["Poison"]},
        {"pokedex_id": 110, "name": "Weezing", "types": ["Poison"]},
        {"pokedex_id": 111, "name": "Rhyhorn", "types": ["Ground", "Rock"]},
        {"pokedex_id": 112, "name": "Rhydon", "types": ["Ground", "Rock"]},
        {"pokedex_id": 113, "name": "Chansey", "types": ["Normal"]},
        {"pokedex_id": 114, "name": "Tangela", "types": ["Grass"]},
        {"pokedex_id": 115, "name": "Kangaskhan", "types": ["Normal"]},
        {"pokedex_id": 116, "name": "Horsea", "types": ["Water"]},
        {"pokedex_id": 117, "name": "Seadra", "types": ["Water"]},
        {"pokedex_id": 118, "name": "Goldeen", "types": ["Water"]},
        {"pokedex_id": 119, "name": "Seaking", "types": ["Water"]},
        {"pokedex_id": 120, "name": "Staryu", "types": ["Water"]},
        {"pokedex_id": 121, "name": "Starmie", "types": ["Water", "Psychic"]},
        {"pokedex_id": 122, "name": "Mr. Mime", "types": ["Psychic", "Fairy"]},
        {"pokedex_id": 123, "name": "Scyther", "types": ["Bug", "Flying"]},
        {"pokedex_id": 124, "name": "Jynx", "types": ["Ice", "Psychic"]},
        {"pokedex_id": 125, "name": "Electabuzz", "types": ["Electric"]},
        {"pokedex_id": 126, "name": "Magmar", "types": ["Fire"]},
        {"pokedex_id": 127, "name": "Pinsir", "types": ["Bug"]},
        {"pokedex_id": 128, "name": "Tauros", "types": ["Normal"]},
        {"pokedex_id": 129, "name": "Magikarp", "types": ["Water"]},
        {"pokedex_id": 130, "name": "Gyarados", "types": ["Water", "Flying"]},
        {"pokedex_id": 131, "name": "Lapras", "types": ["Water", "Ice"]},
        {"pokedex_id": 132, "name": "Ditto", "types": ["Normal"]},
        {"pokedex_id": 133, "name": "Eevee", "types": ["Normal"]},
        {"pokedex_id": 134, "name": "Vaporeon", "types": ["Water"]},
        {"pokedex_id": 135, "name": "Jolteon", "types": ["Electric"]},
        {"pokedex_id": 136, "name": "Flareon", "types": ["Fire"]},
        {"pokedex_id": 137, "name": "Porygon", "types": ["Normal"]},
        {"pokedex_id": 138, "name": "Omanyte", "types": ["Rock", "Water"]},
        {"pokedex_id": 139, "name": "Omastar", "types": ["Rock", "Water"]},
        {"pokedex_id": 140, "name": "Kabuto", "types": ["Rock", "Water"]},
        {"pokedex_id": 141, "name": "Kabutops", "types": ["Rock", "Water"]},
        {"pokedex_id": 142, "name": "Aerodactyl", "types": ["Rock", "Flying"]},
        {"pokedex_id": 143, "name": "Snorlax", "types": ["Normal"]},
        {"pokedex_id": 144, "name": "Articuno", "types": ["Ice", "Flying"]},
        {"pokedex_id": 145, "name": "Zapdos", "types": ["Electric", "Flying"]},
        {"pokedex_id": 146, "name": "Moltres", "types": ["Fire", "Flying"]},
        {"pokedex_id": 147, "name": "Dratini", "types": ["Dragon"]},
        {"pokedex_id": 148, "name": "Dragonair", "types": ["Dragon"]},
        {"pokedex_id": 149, "name": "Dragonite", "types": ["Dragon", "Flying"]},
        {"pokedex_id": 150, "name": "Mewtwo", "types": ["Psychic"]},
        {"pokedex_id": 151, "name": "Mew", "types": ["Psychic"]},
    ]

    for data in pokemon_data_first_generation:
        types = [PokemonType.objects.get_or_create(name=type_name)[0] for type_name in data["types"]]
        try:
            pokemon = Pokemon.objects.create(pokedex_id=data["pokedex_id"], name=data["name"])
            pokemon.types.set(types)
            pokemon.save()
        except ValidationError as e:
            print(f"Validation error for {data['name']}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonTeams', '0002_insert_pokemon_types'),  # Make sure to adjust this based on your actual migration dependencies
    ]

    operations = [
        migrations.RunPython(insert_pokemon_first_generation),
    ]